version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://13.49.23.227:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ell
      - JWT_SECRET=JWT_SECRET:-your_jwt_secret_key
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./backend:/ell
    networks:
      - app-network
    restart: always

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=prodctuion
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  app-network:
    driver: bridge
    name: app-network

